<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Axel T. PYAUTOCAD</title>
    <link rel="stylesheet" href="../css/styles.css">
    <link rel="shortcut icon" type="image/x-icon" href="../img/logo.jpg" />
</head>
<body>
    <!-- Cabecera -->
    <header>
        <!-- Logo -->
        <div>
            <a href="../index.html"><img class="logo" src="../img/logo.jpg" alt="Logo"></a>
        </div>
        <!-- Menu -->
        <nav>
            <ul>
                <li>
                    <a href="../index.html">HOME</a>
                </li>
                <li>
                    <a href="./pyautocad.html">PYAUTOCAD</a>
                </li>
                <li>
                    <a href="./plgraphic.html">PLGRAPHIC</a>
                </li>
                <li>
                    <a href="./ml.html">ML</a>
                </li>
                <li>
                    <a href="./contact.html">CONTACTO</a>
                </li>
            </ul>
        </nav>
    </header>
    <!-- Main -->
    <main class="belowHeader">
        <!-- Encabezado -->
        <h1 class="title">PyAutocad</h1>
        <!-- Tabla de videos -->
        <table class="videoTable" cellpadding="10px" cellspacing="10px">
            <tr>
                <td><iframe width="560" height="315" src="https://www.youtube.com/embed/AVz-yfZ-jcI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></td>
                <td>
                    <h2>APRENDE A AUTOMATIZAR TUS DIBUJOS</h2>
                    <p>¡Hola mundo! Este es el primer video de la serie dedicada a Pyautocad, yo soy Axel y... ¡espero que salga algo bueno!    
                    La misma tiene como objetivo explicar el uso de la librería Pyautocad, la cual es una librería que apunta asimplificar las tareas de automatización en Autocad, a partir del módulo Activex Automation.</p>
                </td>
            </tr>
            <tr>
                <td><iframe width="560" height="315" src="https://www.youtube.com/embed/sTuHd_JyQco" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></td>
                <td>
                    <h2>UN EJEMPLO DE PROGRAMA</h2>
                    <p>En esta ocasión quiero mostrarles un ejemplo de lo que podemos llegar a lograr sabiendo utilizar la librería Pyautocad, para tener una idea de lo que podemos automatizar, para luego entrar de lleno en los comandos que nos permitirán escribir código. 
                    Recomiendo utilizar el IDLE de Pycharm para trabajar con Python, y crear nuestros programas o APIs para Autocad.</p>
                </td>
            </tr>
            <tr>
                <td><iframe width="560" height="315" src="https://www.youtube.com/embed/eWncevMglVo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></td>
                <td>
                    <h2>NUESTRO "HOLA MUNDO"</h2>
                    <p>En este vídeo mostramos la primer función de Pyautocad, muy importante no olvidarse de esta. Además veremos un par de comandos de utilitarios.</p>
                </td>
            </tr>
            <tr>
                <td><iframe width="560" height="315" src="https://www.youtube.com/embed/8HSxpkKIWfU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></td>
                <td>
                    <h2>IMPORTANTE PUNTOS ESPACIALES: Apoint</h2>
                    <p>En este vídeo mostramos cómo definir puntos espaciales desde Pyautocad, muy importante para lo que se viene. También veremos cómo hacer operaciones aritméticas entre puntos que facilitan los cálculos a la hora de programar</p>
                </td>
            </tr>
            <tr>
                <td><iframe width="560" height="315" src="https://www.youtube.com/embed/AenoubmHp2w" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></td>
                <td>
                    <h2>BÁSICO PERO CLAVE COMANDO: AddLine</h2>
                    <p>En este vídeo mostramos cómo graficar líneas mediante Pyautocad de Python . Muy simple pero muy efectivo a la hora de automatizar dibujos en Autocad.</p>
                </td>
            </tr>
        </table>
        <!-- Link para el canal de YT -->
        <section class="middleButton" >
            <a href="https://www.youtube.com/@AxelTag" target="_blank">Mas videos...</a>
        </section>
    </main>
    <!-- Footer -->
    <footer>
        <!-- Menu -->
        <nav>
            <ul>
                <li>
                    <p>Apoya mi contenido:</p>
                </li>
                <li>
                    <a href="https://www.patreon.com/AxelT" target="_blank">PATREON</a>
                </li>
                <li>
                    <a href="https://cafecito.app/axeltonsite" target="_blank">CAFECITO</a>
                </li>
            </ul>
        </nav>
    </footer>
</body>
</html>